apiVersion: v1
kind: Service
metadata:
  name: flask-docker-service
spec:
  selector:
    app: flask-docker
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker
spec:
  selector:
    matchLabels:
      app: flask-docker
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
      containers:
      - name: flask-docker
        image: flask-docker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
